name = "chatwave"
compatibility_date = "2024-03-29"
main = "api/index.ts"

[assets]
directory = "dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "chatwave-db"
database_id = "0b1811f8-6d65-4b18-80e4-d8ecbb1c1abf"

[triggers]
crons = ["0 */12 * * *"]
